---
replicaCount: 1

image:
  repository: xxxxx
  pullPolicy: IfNotPresent
  # Uses Chart.appVersion when empty.
  tag: ""

imagePullSecrets:
  - name: github-secret

nameOverride: ""
fullnameOverride: ""

podLabels: {}

service:
  type: NodePort
  port: 80
  nodePort: 30777

basicAuth:
  # Output of: htpasswd -nb USER PASSWORD
  htpasswd: "test:xxxxxxxxxxxxxxxxxxxx"
