---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "esp-code-resolver.basicAuthSecretName" . }}
  labels:
    {{- include "esp-code-resolver.labels" . | nindent 4 }}
type: Opaque
stringData:
  .htpasswd: |-
    {{- required "basicAuth.htpasswd is required" .Values.basicAuth.htpasswd | nindent 4 }}
