---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "esp-code-resolver.fullname" . }}
  labels:
    {{- include "esp-code-resolver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "esp-code-resolver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "esp-code-resolver.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          volumeMounts:
            - name: basic-auth
              mountPath: /etc/nginx/.htpasswd
              subPath: .htpasswd
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
        - name: basic-auth
          secret:
            secretName: {{ include "esp-code-resolver.basicAuthSecretName" . }}
        - name: nginx-config
          configMap:
            name: {{ include "esp-code-resolver.nginxConfigName" . }}
